# Site settings
title: XFDControl
email: nico@nicolas-byl.eu
description: "eXtreme Feedback made easy."
baseurl: ""
url: "https://nbyl.github.com/xfdcontrol"
github_username:  nbyl

# Build settings
markdown: kramdown
permalink: pretty
